




#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)





In [ ]:
import numpy as np

matrix53=np.random.random((5,3))
matrix32=np.random.random((3,2))
print(np.dot(matrix53, matrix32))

[[0.68864026 1.47708586]
 [0.5781532  1.15651591]
 [0.87132454 1.94529011]
 [0.12128431 0.38980582]
 [0.7547117  1.39387147]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [90]:
matrix1d=np.arange(11)
matrix1d[(3<matrix1d)&(matrix1d<8)] *= -1
print(matrix1d)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9     # -1+0+1+2+3+4

10    # 0+1+2+3+4



#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z (O)
2 << Z >> 2 (O)
Z <- Z  (X)
1j*Z (O)
Z/1/1 (O)
Z<Z>Z (X)
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan

0

array[0]

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1, Z2)
print(np.intersect1d(Z1, Z2))

[3 3 4 3 8 2 9 5 5 6] [9 7 6 8 1 6 9 1 0 6]
[6 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1)==np.emath.sqrt(-1)
#False, np.sqrt(-1)은 nan이 나오고, np.emath.sqrt(-1)는 1j로 표현됨.

<ipython-input-74-3629818e0828>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A=float(input())
B=float(input())

sum=np.add(A, B)
negA=np.negative(A)
div=np.divide(negA, 2)
print(np.multiply(sum, div))

4
5
-18.0


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
a=np.random.uniform(0,10,10)
print(a)
print(a-a%1)
print(a//1)

[6.81339525 1.2104999  7.0531633  3.13130441 0.60607902 0.95574798
 3.55807005 3.3050624  3.67725071 9.14740708]
[6. 1. 7. 3. 0. 0. 3. 3. 3. 9.]
[6. 1. 7. 3. 0. 0. 3. 3. 3. 9.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix55=np.random.uniform(0,4,25).reshape(5,5)
print(matrix55)

[[1.5088693  2.18560034 1.71688433 2.0017593  3.5113566 ]
 [2.53384549 1.88967007 2.82288958 1.6863589  3.54399448]
 [1.89060057 3.95883576 3.56080897 2.35597422 0.51453607]
 [1.28058622 3.1909148  2.20661978 0.10139672 0.77668714]
 [1.87716102 2.40239289 1.92673231 0.80460895 0.21896271]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
random10=np.random.random(10)
print(np.sort(random10))

[0.08433638 0.1877234  0.33413848 0.4121747  0.45702803 0.46454755
 0.50871251 0.70519442 0.76595769 0.83078884]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
random102=np.random.random((10,2))
x=random102[:,0]
y=random102[:,1]
distance=np.sqrt(x**2+y**2)
angle=np.arctan2(y,x)
print(distance)
print(angle)

[0.22064561 0.53796195 0.58521709 1.21609807 0.76017233 0.68291135
 0.4747595  0.6082744  0.69109639 0.82715735]
[1.39548206 0.74648294 1.39365048 0.70145848 1.24354088 1.07558736
 0.72117674 0.26690375 0.76847649 0.72415065]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)

[0.32086575 0.53305477 0.         0.32184708 0.60335555 0.25898622
 0.24287143 0.6541131  0.44781063 0.02984302]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Compute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dis=np.abs(Z-v)
print(Z[np.argmin(dis)])

42


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 9
p = 8
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 3)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 3. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0. 3. 0. 3. 3.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[7 6 2]
 [6 9 2]
 [8 7 0]]
[[6 9 2]
 [7 6 2]
 [8 7 0]]


In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3