### **01-03. Numpy**
Numpy(Numerical Python)은 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지로, 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 함으로 빠른 배열 연산 속도를 보장한다. 또한, 넘파이는 C/C++과 같은 저수준 언어 기반의 호환 API를 제공한다. 수행성능이 중요한 부분은 C/C++기반의 코드로 작성하고 이를 넘파이에서 호출하는 방식으로 쉽게 통합할 수 있다.

알고리즘의 입력 데이터와 출력 데이터를 넘파이 배열 타입으로 사용하기 때문에 넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요하다. 또한 넘파이가 배열을 다루는 기본 방식을 이해하는 것은 다른 데이터 핸들링 패키지(예:판다스)를 이해하는 데도 많은 도움이 된다.  






---



- 넘파이의 개요
- ndarray의 데이터 타입
- ndarray 편리하게 생성하기
- ndarray 차원과 크기 변경하기
- ndarray에서 인덱싱(indexing)하기
- 행렬 정렬하기
- 선형대수 연산하기


---



**넘파이의 개요**

   ndarray는 넘파이의 기반 데이터 타입이다.

- nd.array(): 인자를 입력받아서 ndarray로 변환

- ndarray.shape: 행과 열의 수를 튜플 형태로 표현

- ndarray.dim: 차원 차수 확인

- type(array): <class 'numpy.ndarray'> 반환


In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print('array1 type：', type(array1))
print('array1 array 형태:', array1.shape)


array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type：', type(array2))
print('array2 array 형태：', array2.shape)


array3 = np.array([[1, 2, 3]])
print('array3 type：', type(array3))
print('array3 array 형태:', array3.shape)

array1 type： <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type： <class 'numpy.ndarray'>
array2 array 형태： (2, 3)
array3 type： <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1:{0}차원, array2:{1}차원, array3:{2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3:2차원


**ndarray의 데이터 타입**

   숫자 값(int형, unsigned int형, float형), 문자열 값, 불 값 모두 가능하다.
   다만, 한 개의 ndarray 객체엔 하나의 데이터 타입만 가능하다.

- ndarray.dtype: ndarray내의 데이터 타입 확인  
   예) int32, float64

In [ ]:
list1=[1,2,3]
print(type(list))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'type'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
# 다른 데이터 유형이 섞여있으면 데이터 크기가 더 큰 데이터 타입으로 변환됨.
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)
list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
# ndarray.astype(): 데이터 타입을 변환. 보통 메모리를 절약해햐할 때 이용됨.
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**ndarray를 편리하게 생성하기**

- arange(): 0부터 (인자값-1)까지의 값을 순차적으로 데이터값으로 가지는 ndarray 반환
- zeros(): 모든 값을 0으로 채운 shape의 ndarray 반환
- ones(): 모든 값을 1로 채운 shape의 ndarray 반환

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 차원과 크기를 변경하기**

데이터값으론 동일하지만 차원이 달라서 오류가 발생하는 경우가 많기 때문에 차원의 차수를 정확히 변환할 줄 아는 것이 중요하다.
- 함수 reshape() 사용.

In [ ]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 지정된 사이즈로 변경이 불가능하면 오류가 발생함.
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
# 사이즈 지정에 -1을 인자로 사용하면 원래 ndarray와 호환되는 shape로 변환해줌.
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
# 마찬가지로 10개의 1차원 데이터를 4개의 column을 가진 row로는 변경할 수 없기 때문에 오류가 발생함.
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원을 2차원으로 변환
array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원을 2차원으로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


**ndarray에서 인덱싱(Indexing)하기**

-단일값 추출: 원하는 특정한 위치의 데이터를 추출

-슬라이싱(Slicing): 1:5라고 하면 인덱스 1,2,3,4에 해당하는 ndarray 반환.

-팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환.

-불린 인덱싱(Boolean Indexing): 특정 조건에 대하여 True/False값 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터를 ndarray로 반환.


In [ ]:
# 단일값 추출

array1=np.arange(start=1, stop=10)   #1부터 9까지의 1차원 ndarray 생성
print('array1:', array1)
value=array1[2]     # index는 0부터 시작하므로 array1[2]는 3번째 위치의 데이터를 의미
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
# ndarray 내의 데이터값 수정

array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
# 다차원 ndarray에서 단일값 추출
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [ ]:
# 슬라이싱(Slicing)

array1=np.arange(start=1, stop=10)
array3=array1[0:3]     # 인덱스 0,1,2에 해당하는 데이터를 ndarray형태로 반환
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]     # ':'앞 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
print(array4)

array5=array1[3:]     # ':'뒤 인덱스를 생략하면 맨 마지막 인덱스로 간주
print(array5)

array6=array1[:]      # ':'만 있으면 자동으로 전체 인덱스로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 2차원 ndarray에서의 슬라이싱
# array[:,:] 형식. 차례대로 row, column에 해당.

array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,2:0]\n', array2d[0:2,0:2])
print('array2d[1:3,0:3]\n', array2d[1:3,0:3])
print('array2d[1:3,:]\n', array2d[1:3,:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,2:0]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [ ]:
# 2차원에서 뒤에 오는 인덱스를 없애면 axis0(row축)의 첫번째 row를 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [ ]:
# 팬시 인덱싱(Fancy Indexing)
# array[[,,], :] 형식으로 사용 가능

array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


In [ ]:
# 불린 인덱싱 (Boolean Indexing)
# 순서: 1) array1d>5 Boolean 조건을 []내에 입력
#       2) False 값은 무시하고 True 값에 해당하는 index값만 저장
#       3) 저장된 index값으로 데이터 조회

array1d=np.arange(start=1, stop=10)
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes=np.array([False, False, False, False, False, True, True, True, True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [ ]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


**행렬 정렬하기 - sort()**
- np.sort(): 원행렬은 그대로 유지, 정렬된 행렬을 반환
- ndarray.sort(): 원행렬 자체를 정렬한 형태로 바꿈, None을 반환


In [ ]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
# np.sort()[::-1]은 내림차순으로 정렬하여 반환
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
# ndarray가 2차원 이상일 경우 axis축 설정
# axis0은 row, axis1은 column

array2d=np.array([[8,12],
                  [7,1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


**행렬 정렬하기 - np.argsort()**

   np. argsort()는 numpy에서 활용도가 매우 높다.
- np.argsort(): 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 ndarray형태로 반환.


In [ ]:
# 정렬 시 원본 행렬의 인덱스 반환
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
# np.argsort()[::-1]으로 내림차순으로 정렬 시 원본 행렬의 인덱스 반환
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
# 시험 성적순으로 학생 이름을 출력하고자 한다면, np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해서 추출.
import numpy as np
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])


성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


**선형대수 연산하기**
- np.dot(): 행렬의 내적
- np.transpose(): 전치 행렬 반환

In [ ]:
#행렬 내적(행렬의 곱)
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [ ]:
#전치 행렬
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
