# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [14]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
print(vector.nbytes)

80

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
vector = np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector2=np.arange(start=10, stop=50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
print(np.sort(vector2)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
matrix=np.arange(start=0,end=9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [22]:
vector3=np.array([1,2,0,0,4,0])
indices=vector3[vector3!=0]
print(indices)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [24]:
np.random.random((3,3,3))

array([[[0.42525602, 0.99663597, 0.37047884],
        [0.25912935, 0.64497656, 0.12179742],
        [0.97523243, 0.66062371, 0.31501358]],

       [[0.22643626, 0.17264324, 0.52018369],
        [0.2225542 , 0.43653675, 0.45082724],
        [0.00145328, 0.27315709, 0.86958518]],

       [[0.45721636, 0.70197714, 0.59120951],
        [0.86745522, 0.92846035, 0.02929204],
        [0.87581763, 0.86198851, 0.99721603]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [28]:
array=np.random.random((10,10))
print(np.min(array), np.max(array))

0.014030978414778406 0.9989017514416872


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [29]:
random_vector=np.random.random(30)
print(np.mean(random_vector))

0.6511712010276749


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [31]:
array2=np.zeros((6,6))
array2[0,:]=1
array2[:,0]=1
array2[-1,:]=1
array2[:,-1]=1
print(array2)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan

False

False

nan

False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [34]:
matrix2=np.zeros((5,5))
matrix2[1,0]=1
matrix2[2,1]=2
matrix2[3,2]=3
matrix2[4,3]=4
print(matrix2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [37]:
matrix3=np.zeros((8,8))
matrix3[1::2,::2]=1
matrix3[::2,1::2]=1
print(matrix3)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [38]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [40]:
matrix4=np.random.random((5,5))
matrix4_mean=np.mean(matrix4)
matrix4_std=np.std(matrix4)
matrix4_n=(matrix4-matrix4_mean)/matrix4_std
print(matrix4_n)

[[-0.78357821 -0.90812534  1.22628861 -0.65526264  0.0197987 ]
 [-1.29012966 -1.32245772  1.53201451  1.85932593  1.3659894 ]
 [-0.96586253  0.75448783 -0.84941735  0.98178202  0.97873393]
 [ 0.82293292  1.06073861 -0.12820731 -0.47278665 -0.56841526]
 [-0.40502509 -1.42178699  0.31994087 -1.31141604  0.16043744]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [41]:
dtype_RGBA=np.dtype([('R',np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
print(dtype_RGBA)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]
