




#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)





In [53]:
import numpy as np
matrix53=np.random.random((5,3))
matrix32=np.random.random((3,2))
print(matrix53.dot(matrix32))

[[0.70196466 0.57336969]
 [0.63651159 0.55167915]
 [0.33493065 0.28831484]
 [0.92379395 0.72750352]
 [0.7052975  0.63215243]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [54]:
matrix1d=np.arange(11)
matrix1d[(3<matrix1d)&(matrix1d<8)] *= -1
print(matrix1d)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9     # -1+0+1+2+3+4

10    # 0+1+2+3+4



#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z (O)
2 << Z >> 2 (O)
Z <- Z  (X)
1j*Z (O)
Z/1/1 (O)
Z<Z>Z (X)
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan

0

array[0]

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [55]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1, Z2)
print(np.intersect1d(Z1, Z2))

[8 9 7 4 6 8 4 2 4 1] [2 7 0 3 5 1 0 1 6 9]
[1 2 6 7 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [56]:
np.sqrt(-1)==np.emath.sqrt(-1)
#False, np.sqrt(-1)은 nan이 나오고, np.emath.sqrt(-1)는 1j로 표현됨.

<ipython-input-56-3629818e0828>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [57]:
Z=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [58]:
A=float(input())
B=float(input())

sum=np.add(A, B)
negA=np.negative(A)
div=np.divide(negA, 2)
print(np.multiply(sum, div))

4
5
-18.0


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [59]:
a=np.random.uniform(0,10,10)
print(a)
print(a-a%1)
print(a//1)

[4.25076849 5.9679259  5.92462623 9.2592125  0.73340854 9.93617005
 3.83232169 0.3020354  5.82431503 7.28789582]
[4. 5. 5. 9. 0. 9. 3. 0. 5. 7.]
[4. 5. 5. 9. 0. 9. 3. 0. 5. 7.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [60]:
matrix55=np.random.uniform(0,4,25).reshape(5,5)
print(matrix55)

[[3.56856637 2.02862749 1.80213987 0.40343643 2.53692438]
 [3.27016087 1.36460045 3.25541628 2.32123958 0.42005614]
 [3.90585069 3.16433221 2.54727026 3.26956569 2.1256026 ]
 [2.29400723 1.9959748  1.61889422 2.75007078 3.76345427]
 [2.72360298 3.61076112 1.58453766 2.10865355 1.6918757 ]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [61]:
random10=np.random.random(10)
print(np.sort(random10))

[0.03115923 0.23077635 0.24510535 0.27909763 0.36487034 0.38160032
 0.4850352  0.48610476 0.89613651 0.96582106]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [62]:
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [63]:
random102=np.random.random((10,2))
x=random102[:,0]
y=random102[:,1]
distance=np.sqrt(x**2+y**2)
angle=np.arctan2(y,x)
print(distance)
print(angle)

[1.17410374 0.86718732 0.22424323 0.85339186 1.1771497  0.99433969
 1.01546431 0.79735306 0.72172608 1.28011412]
[0.97963211 1.12455435 0.6062994  1.51953538 0.6580631  0.33021319
 0.56047972 1.22807426 0.01682196 0.82842658]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [64]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)

[0.         0.46850054 0.81840776 0.6887146  0.60168874 0.29832766
 0.16016636 0.30313555 0.10387707 0.33327456]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Compute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [65]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dis=np.abs(Z-v)
print(Z[np.argmin(dis)])

18


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [47]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [66]:
n = 9
p = 8
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 3)
print(Z)

[[0. 0. 0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 3. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0. 3. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [67]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[5 5 8]
 [0 2 2]
 [4 0 5]]
[[0 2 2]
 [4 0 5]
 [5 5 8]]


In [52]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3